import { execOnce } from "next/dist/next-server/lib/utils";

export const GET_PRODUCT_DETAIL_ID = 'GET_PRODUCT_DETAIL_ID';
export const GET_PRODUCT_DETAIL_ID_ERROR = "GET_PRODUCT_DETAIL_ID_ERROR";
export const GET_PRODUCT_CATEGORY = 'GET_PRODUCT_CATEGORY';
export const GET_PRODUCT_CATEGORIES = 'GET_PRODUCT_CATEGORIES';
export const GET_PRODUCT_BRANDS = 'GET_PRODUCT_BRANDS';
export const GET_BRAND_PRODUCTS = 'GET_BRAND_PRODUCTS';
export const GET_PRODUCT_SUBCATEGORY = 'GET_PRODUCT_SUBCATEGORY';
export const GET_PRODUCTLIST = 'GET_PRODUCTLIST';
export const GET_SEARCH_PRODUCT = 'GET_SEARCH_PRODUCT';
export const GET_SEARCH_PRODUCT_NAME = 'GET_SEARCH_PRODUCT_NAME';
export const LOAD_MORE = 'LOAD_MORE';
export const GET_SIMILAR_PRODUCT = 'GET_SIMILAR_PRODUCT';