import LocalizedStrings from 'react-localization';

export default new LocalizedStrings({
  en: {
    youWannaSell: 'Do you wanna sell items?',
    guide: 'As a first time user, it’s important for us to guide you what do you wanna do.',
    note:
      'Note - This screen will only be seen right now and after that, you will not be seen anymore.',
    searchProducts: 'Search Products Here',
    search: 'SEARCH',
    recentSearches: 'Recent Searches',
    goToMerchant: 'GO TO MERCHANT',
    theProduct: 'The product you are trying to search is currently unavailable... ',
    shop: 'SHOP',
    getApp: 'GET APP',
    wishList: 'WISH LIST',
    account: 'ACCOUNT',
    yourCart: 'Your Cart',
    aboutUs: 'About us',
    ourServices: 'Our Services',
    helpFAQs: 'Help & FAQs',
    information: 'Information',
    contactUs: 'Contact Us',
    downloadApp: 'Download App',
    goToMerchant: 'GO TO MERCHANT',
    goStore: 'Go Store',
    home: 'HOME',
    products: 'PRODUCTS',
    contacts: 'CONTACTS',
    comments: 'COMMENTS',
    feedback: 'FEEDBACK',
    items: '1 items found in Car accessories shop',
    follow: 'Follow',
    positiveFeedback: 'Positive Feedback',
    followers: 'Followers',
    shopInformation: 'Shop Information',
    name: 'Name',
    rmail: 'Email',
    phoneNumber: 'Phone Number',
    address: 'Address',
    country: 'Country/Region',
    city: 'City',
    contact: 'Contact',
    startOrder: 'Start Order',
    contactInformation: 'Contact Information',
    shopName: 'Shop Name',
    address: 'Address',
    website: 'Website',
    callCenter: 'Call Center',
    itemsFoundIn: 'items found in',
    loadMore: 'Load More',
    noProduct: 'NO PRODUCT IS AVALIBLE RIGHT NOW:(',
    selectedProducts:
      'You have already selected products from a different shop. If you continue, your cart and selection will be removed. ',
    cancel: 'CANCEL',
    buyNow: 'Buy Now',
    addedTheProduct: 'Successfully added the product',
    brand: 'Brand',
    color: 'Color',
    size: 'Size',
    weight: 'Weight',
    product: 'Product',
    quantity: 'Quantity',
    itemIsLimited: 'Item is Limited',
    buyNow: 'Buy Now',
    addToCart: 'Add To Cart',
    selectAll: 'SELECT ALL',
    delete: 'DELETE',
    noProduct: 'No Product is here',
    orderSummary: 'Order Summary',
    subtotal: 'Subtotal',
    shippingFees: 'Shipping Fees',
    total: 'Total',
    proceed: 'Proceed To Checkout',
    check: 'Please check the product',
    lists: 'ITEM LISTS',
    deliveryInformation: 'Delivery Information',
    fullName: 'Full Name',
    address: 'Address',
    selectRegion: 'Select Region',
    selectTownship: 'Select Township',
    selectWard: 'Select Ward',
    label: 'Select a label for effective delivery',
    home: 'HOME',
    office: 'Office',
    save: 'Save',
    field: 'This Field is required',
    long: 'Too Long',
    number: 'It must be number',
    refillDelivery: 'Please re-fill the delivery information',
    login: 'LOGIN',
    logout: 'Logout',
    phoneNumber: 'Please Enter your Phone Number. ',
    otpMobileNumber: 'OTP is sent to your mobile Number',
    pleaseType: 'Please type your OTP number',
    resend: 'Resend',
    billingAddress: 'Billing Address',
    fullName: 'Full Name',
    address: 'Address',
    region: 'Region',
    phone: 'Phone',
    addNewAddress: 'Add New Address',
    cancel: 'CANCEL',
    save: 'SAVE',
    deliveryOptions: 'Preferred Delivery Options',
    paymentInformation: 'Payment Information',
    merchantName: 'Merchant Name',
    productDescription: 'Product Description',
    invoiceNumber: 'Invoice Number',
    amount: 'Amount',
    cardNumber: 'Card Number',
    month: 'Month',
    year: 'Year',
    enterOtp: 'Enter Otp',
    getOtp: 'Get OTP',
    cancel: 'CANCEL',
    confirm: 'CONFIRM PAYMENT',
    instructions: 'INSTRUCTIONS FOR AYA PAY',
    open:
      '1. Please open your AYA Pay account. (If you dont have an AYA Pay account, you can download it on ayapay.com).',
    Login:
      '2. Login to your AYA Pay account with your phone number. (If you aren’t register to AYA Pay account yet, please register AYA Pay account).',
    openQr: '3. Please open your QR code scanner and scan QR code in order to pay the amount.',
    enter: '4. Please enter your PIN number for the payment verification.',
    yourProfile: 'YOUR PROFILE',
    information: 'INFORMATION',
    fullName: 'Full Name',
    address: 'Address',
    email: 'Email',
    orderHistory: 'ORDER HISTORY',
    yourOrder: 'YOUR ORDER ID',
    quantity: 'Quantity',
    status: 'STATUS',
    amount: 'AMOUNT',
    orderItem: 'Order item is not found',
    profile:'Profile',
    logout:'LOG OUT',
    phone:'Phone Number',
    checkout:'Check Out',
    limited:'Item is limited',
    place:'Place Order',
    billingAddress:'Billing Address',
    newAddress:'Add New Address',
    recent:'Recent Searches',
    notFound:'Product is not found',
    noProducts:'No Product Available',
    checkoutProducts:'Checkout Products',
    service:'Delivery Service not available!',
    edit:'Edit',
    checkout:'Check Out'
    
    },
    mm: {
    youWannaSell: 'ကုန်ပစ္စည်းရောင်းချင်ပါသလား',
    guide: 'ပထမ ဦး ဆုံးအကြိမ်အသုံးပြုသူများကို ညွှန်ပြပေးဖို့ ကျွနိုပ်တို့တွင် တာဝန်ရှိပါတယ်',
    note:
      'မှတ်ချက် - ဒီမျက်နှာပြင်ကိုအခုအချိန်မှာပဲမြင်တွေ့ရမှာဖြစ်ပါတယ်။ နောက်တဖန်မမြင်ရနိင်တော့ပါ။',
    searchProducts: 'ကုန်ပစ္စည်းများရှာဖွေမည်',
    search: 'ရှာမည်',
    recentSearches: 'လတ်တလောရှာဖွေမှုများ',
    goToMerchant: 'ကုန်ပစ္စည်းများရောင်းချမည်။',
    theProduct: 'သင်ရှာဖွေနေသောကုန်ပစ္စည်းသည်လောလောဆယ်မရရှိနိုင်ပါ။',
    shop: 'ဆိုင်များ',
    getApp: 'App ရယူရန်',
    wishList: 'အကြိုက်ဆုံးပစ္စည်းစာရင်း',
    account: 'စာရင်းသွင်းရန်',
    yourCart: 'ခြင်းတောင်းသို့',
    aboutUs: 'ကျွန်ုပ်တို့အကြောင်း',
    ourServices: 'ဝန်ဆောင်မှုများ',
    helpFAQs: 'အကူအညီ',
    information: 'သတင်းအချက်အလက်',
    contactUs: 'ဆက်သွယ်ရန်',
    downloadApp: 'App ရယူပါ',
    goToMerchant: 'ကုန်ပစ္စည်းများရောင်းချမည်',
    goStore: 'ဆိုင်ထဲသို့ဝင်ကြည့်ရန်',
    home: 'ပင်မစာမျက်နှာ',
    products: 'ကုန်ပစ္စည်းများ',
    contacts: 'ဆက်သွယ်ရန်',
    comments: 'မှတ်ချက်များ',
    feedback: 'ဝေဖန်အကြံပြုစာ',
    items: 'ဤဆိုင်တွင် ကုန်ပစ္စည်း(၁)ခုသာ ရှိသည်',
    follow: 'စောင့်ကြည့်မည်',
    positiveFeedback: 'အပြုသဘောတုံ့ပြန်ချက်',
    followers: 'စောင့်ကြည့်သူများ',
    shopInformation: 'ဆိုင်အကြောင်းအရာ',
    name: 'နာမည်',
    rmail: 'အီးမေးလ်',
    phoneNumber: 'ဖုန်းနံပါတ်',
    address: 'လိပ်စာ',
    country: 'တိုင်းဒေသကြီး',
    city: ' မြို့နယ်',
    contact: 'ဆက်သွယ်ရန်',
    startOrder: 'စတင်ဝယ်ယူမည်',
    contactInformation: 'ဆက်သွယ်ရန်အချက်အလက်',
    shopName: 'ဆိုင်အမည်',
    address: 'လိပ်စာ',
    website: 'ဝဘ်ဆိုက်',
    callCenter: 'ဆက်သွယ်ရန်',
    itemsFoundIn: 'မှရရှိနိုင်သောပစ္စည်းများ',
    loadMore: 'ပိုမိုလေ့လာရန်',
    noProduct: 'ကုန်ပစ္စည်းများ မရရှိနိုင်သေးပါ',
    selectedProducts:
      'တခြားဆိုင်တစ်ဆိုင်မှကုန်ပစ္စည်းများကိုရွေးချယ်ပြီးဖြစ်သည်။ ဆက်လက်လုပ်ဆောင်လျှင် ရွေးချယ်ထားသည့်ကုန်ပစ္စည်းများကို ပယ်ဖျက်ရမည်။',
    cancel: 'မလုပ်ဆောင်တော့ပါ',
    buyNow: 'ဝယ်မည်',
    addedTheProduct: 'ကုန်ပစ္စည်းကိုခြင်းတောင်းထဲသို့ထည့်ပြီးပါပြီ',
    brand: 'ကုန်အမှတ်တံဆိပ်',
    color: 'အရောင်',
    size: 'အရွယ်အစား',
    weight: 'အလေးချိန်',
    product: 'ကုန်ပစ္စည်း',
    quantity: 'အရေအတွက်',
    itemIsLimited: 'ပစ္စည်းအကန့်အသတ်ရှိသည်။',
    buyNow: 'ဝယ်မည်',
    addToCart: 'ခြင်းတောင်းသို့',
    selectAll: 'အားလုံးကိုရွေးချယ်မည်',
    delete: 'ဖျက်သိမ်းမည်',
    noProduct: 'ကုန်ပစ္စည်းမရှိသေးပါ',
    orderSummary: 'အော်ဒါအကျဉ်းချုပ်',
    subtotal: 'စုစုပေါင်း',
    shippingFees: 'ပြည်တွင်းတင်သွင်းခ',
    total: 'စုစုပေါင်း',
    proceed: 'ငွေရှင်းရန်ဆက်လက်လုပ်ဆောင်ပါ',
    check: 'ကျေးဇူးပြုပြီးကုန်ပစ္စည်းကိုစစ်ဆေးပါ',
    lists: 'ပစ္စည်းစာရင်း',
    deliveryInformation: 'ကုန်ပစ္စည်းပေးပို့ရမည့်အချက်အလက်',
    fullName: 'နာမည်အပြည့်အစုံ',
    address: 'လိပ်စာ',
    selectRegion: 'တိုင်းဒေသကြီးရွေးပါ',
    selectTownship: 'မြို့နယ်ရွေးပါ',
    selectWard: 'ရပ်ကွက်ရွေးပါ',
    label: 'ပေးပို့ရမည့်နေရာအား ရွေးချယ်ပါ',
    home: 'အိမ်',
    office: 'ရုံး',
    save: 'သိမ်းဆည်းမည်',
    deliveryOptions: 'ပေးပို့ရမည့်စနစ်',
    paymentInformation: 'ငွေပေးချေရန်အချက်အလက်',
    merchantName: 'ကုန်သည်အမည်',
    productDescription: 'ကုန်ပစ္စည်းအကြောင်းအရာ',
    invoiceNumber: 'ငွေတောင်းခံလွှာအမှတ်',
    Amount: 'ငွေပမာဏ',
    cardNumber: 'ကတ်နံပါတ်',
    month: 'လ',
    year: 'နှစ်',
    enterOtp: 'OTP ထည့်ပါ',
    getOtp: 'OTP ရယူပါ',
    cancel: 'ပယ်ဖျက်ပါ',
    confirm: 'ငွေပေးချေမှုအား အတည်ပြုမည်',
    instructions: 'AYA ငွေပေးချေရန်အတွက်ညွှန်ကြားချက်များ',
    open:
      '၁။ ကျေးဇူးပြု၍ သင်၏ AYA Pay အကောင့်ကိုဖွင့်ပါ။ (AYA Pay အကောင့်မရှိလျှင်၊ ayapay.com တွင်ကူးယူနိုင်သည်)',
    login:
      '၂။ သင်၏ဖုန်းနံပါတ်နှင့်သင်၏ AYA Pay အကောင့်သို့ဝင်ပါ။ (အကယ်၍ သင် AYA Pay အကောင့်ကိုမှတ်ပုံတင်မထားရင်၊ ကျေးဇူးပြု၍ AYA Pay အကောင့်ကိုမှတ်ပုံတင်ပါ။',
    openQr:
      '၃။ ကျေးဇူးပြု၍ သင်၏ QR ကုဒ်ကိုဖွင့်ပါ ငွေပမာဏကိုပေးဆောင်နိုင်ရန်အတွက် QR ကုဒ်ကိုစကင်ဖတ်စစ်ဆေးပါ',
    enter: '၄။ ငွေပေးချေမှုအတည်ပြုချက်အတွက်သင်၏ PIN နံပါတ်ကိုဖြည့်ပါ။.',
    yourProfile: 'ကိုယ်ရေးရာဇဝင်အချက်အလက်',
    information: 'သတင်းအချက်အလက်',
    fullName: 'နာမည်အပြည့်အစုံ',
    address: 'လိပ်စာ',
    email: 'အီးမေးလ်',
    orderHistory: 'အော်ဒါအမှာစာများ',
    yourOrder: 'ငွေတောင်းခံလွှာအမှတ်',
    quantity: 'အရေအတွက်',
    status: 'အခြေအနေ',
    amount: 'ပမာဏ',
    orderItem: 'အော်ဒါပစ္စည်းရှာမတွေ့ပါ',
    profile: 'ပရိုဖိုင်',
    login: 'ဝင်ရန် ',
    logout: 'ထွက်ရန်',
    phone: 'ဖုန်းနံပါတ်',
    checkout: 'ဆက်လက်လုပ်ဆောင်ပါ',
    limited:'ပစ္စည်းအကန့်အသတ်ရှိသည်။',
    place:'အော်ဒါတင်မည်',
    billingAddress:'ငွေတောင်းခံရန်လိပ်စာ',
    newAddress:'လိပ်စာအသစ်ထည့်ပါ',
    recent:'လတ်တလောရှာဖွေမှုများ',
    noProducts:'ကုန်ပစ္စည်းများ မရရှိနိုင်သေးပါ',
    notFound:'ပစ္စည်းရှာမတွေ့ပါ',
    checkoutProducts:'ကုန်ပစ္စည်းကိုစစ်ဆေးပါ',
    service:'Delivery မရှိသေးပါ',
    edit:'ပြင်ရန်',
    checkout:'ေငြရွင္းမည္'
     },
});
