export const township = [
  { label: 'Ahlon', value: 'Ahlon' },
  { label: 'Bahan', value: 'Bahan' },
  { label: 'Botataung', value: 'Botataung' },
  { label: 'Dagon', value: 'Dagon' },
  { label: 'Dagon Seikkan', value: 'Dagon Seikkan' },
  { label: 'Dawbon', value: 'Dawbon' },
  { label: 'Dala', value: 'Dala' },
  { label: 'Hlaing', value: 'Hlaing' },
  { label: 'Hlaingthaya', value: 'Hlaingthaya' },
  { label: 'Insein', value: 'Insein' },
  { label: 'Kamayut', value: 'Kamayut' },
  { label: 'Kyauktada', value: 'Kyauktada' },
  { label: 'Kyimyindaing', value: 'Kyimyindaing' },
  { label: 'Lanmadaw', value: 'Lanmadaw' },
  { label: 'Latha', value: 'Latha' },
  { label: 'Mayangon', value: 'Mayangon' },
  { label: 'Mingala Taungnyunt', value: 'Mingala Taungnyunt' },
  { label: 'Mingaladon', value: 'Mingaladon' },
  { label: 'New Dagon East', value: 'New Dagon East' },
  { label: 'New Dagon North', value: 'New Dagon North' },
  { label: 'New Dagon South', value: 'New Dagon South' },
  { label: 'North Okkalapa', value: 'North Okkalapa' },
  { label: 'Pabedan', value: 'Pabedan' },
  { label: 'Pazundaung', value: 'Pazundaung' },
  { label: 'Sanchaung', value: 'Sanchaung' },
  { label: 'South Okkalapa', value: 'South Okkalapa' },
  { label: 'Seikkyi Kanaungto', value: 'Seikkyi Kanaungto' },
  { label: 'Tamwe', value: 'Tamwe' },
  { label: 'Thaketa', value: 'Thaketa' },
  { label: 'Thingangyun', value: 'Thingangyun' },
  { label: 'Shwepyitha', value: 'Shwepyitha' },
  { label: 'Yankin', value: 'Yankin' },
];

export const city = [{ label: 'Yangon', value: 'Yangon' }];
export const Region = [{ label: 'Yangon', value: 'Yangon' }];
